spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/diwei_jin?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: jindiwei
    password: qBgWCGUbsM9M
    platform: mysql
    initialize: false